import React, { useState } from 'react';
import { FileText, Download, Clock, MapPin, Phone, ChevronDown, ChevronUp } from 'lucide-react';

export default function AccidentReport({ location, address, pois }) {
  const [isOpen, setIsOpen] = useState(false);
  const [report, setReport] = useState(null);

  const generateReport = () => {
    const now = new Date();

    const reportData = {
      id: `RSoS-${now.getFullYear()}${(now.getMonth()+1).toString().padStart(2,'0')}${now.getDate().toString().padStart(2,'0')}-${Math.random().toString(36).substr(2, 6).toUpperCase()}`,
      timestamp: now.toLocaleString('en-IN', { dateStyle: 'full', timeStyle: 'medium' }),
      location: location ? `${location.lat.toFixed(6)}, ${location.lng.toFixed(6)}` : 'Not available',
      address: address?.display_name || 'Not available',
    };
    setReport(reportData);
  };

  const downloadReport = () => {
    if (!report) return;

    const text = `
═══════════════════════════════════════════
       ROADSOS — ACCIDENT REPORT
═══════════════════════════════════════════

Report ID:    ${report.id}
Generated:    ${report.timestamp}

───────────────────────────────────────────
  ACCIDENT LOCATION
───────────────────────────────────────────
GPS:          ${report.location}
Address:      ${report.address}
Maps Link:    https://www.google.com/maps?q=${location?.lat},${location?.lng}

───────────────────────────────────────────
  EMERGENCY NUMBERS
───────────────────────────────────────────
  Ambulance:    108
  Police:       100
  Fire:         101
  Universal:    112

═══════════════════════════════════════════
  This report was auto-generated by RoadSoS
  https://roadsos.app
═══════════════════════════════════════════
`.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `RoadSoS_Report_${report.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareReport = async () => {
    if (!report) return;
    const shareText = `🚨 ROADSOS ACCIDENT REPORT\n📍 ${report.address}\n🗺️ https://www.google.com/maps?q=${location?.lat},${location?.lng}\n🕐 ${report.timestamp}\n📞 Emergency: 112 | Ambulance: 108 | Police: 100\nReport ID: ${report.id}`;
    
    if (navigator.share) {
      try {
        await navigator.share({ title: 'RoadSoS Accident Report', text: shareText });
      } catch (e) { /* user cancelled */ }
    } else {
      await navigator.clipboard.writeText(shareText);
      alert('Report copied to clipboard!');
    }
  };

  return (
    <div className="bg-gradient-to-br from-white to-amber-50 dark:from-gray-800 dark:to-gray-900 rounded-2xl shadow-md border border-amber-200 dark:border-amber-900 overflow-hidden transition-all duration-300 hover:shadow-lg">
      <button 
        onClick={() => { setIsOpen(!isOpen); if (!report) generateReport(); }}
        className="w-full p-4 flex items-center justify-between"
      >
        <div className="flex items-center space-x-3">
          <div className="p-2 bg-amber-100 text-amber-600 rounded-full">
            <FileText size={20} />
          </div>
          <div className="text-left">
            <p className="font-bold text-gray-900 dark:text-white text-sm">Accident Report Generator</p>
            <p className="text-xs text-gray-500">Auto-generate a shareable report with GPS & contacts</p>
          </div>
        </div>
        {isOpen ? <ChevronUp size={20} className="text-gray-400" /> : <ChevronDown size={20} className="text-gray-400" />}
      </button>

      {isOpen && report && (
        <div className="px-4 pb-4 space-y-3 border-t dark:border-gray-700 pt-3">
          <div className="bg-gray-50 dark:bg-gray-900 rounded-xl p-3 space-y-2 text-sm">
            <div className="flex items-center space-x-2 text-gray-600 dark:text-gray-300">
              <Clock size={14} />
              <span>{report.timestamp}</span>
            </div>
            <div className="flex items-center space-x-2 text-gray-600 dark:text-gray-300">
              <MapPin size={14} />
              <span className="truncate">{report.address}</span>
            </div>
            <p className="text-[10px] font-mono text-gray-400 pt-1">ID: {report.id}</p>
          </div>

          <div className="flex space-x-2">
            <button 
              onClick={downloadReport}
              className="flex-1 flex items-center justify-center space-x-2 bg-amber-600 text-white py-2.5 rounded-xl font-bold text-sm hover:bg-amber-700 transition"
            >
              <Download size={16} />
              <span>Download</span>
            </button>
            <button 
              onClick={shareReport}
              className="flex-1 flex items-center justify-center space-x-2 bg-blue-600 text-white py-2.5 rounded-xl font-bold text-sm hover:bg-blue-700 transition"
            >
              <FileText size={16} />
              <span>Share</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
